backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "link"
    label: "Link"
    folder: "_links"
    editor:
      preview: false
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - name: ltype
        label: "Link Type"
        widget: select
        options:
          - label: Video
            value: Video
          - label: Audio
            value: Audio
          - label: Article
            value: Article
          - label: Other
            value: Other
      - label: "Title"
        name: "title"
      - label: "Tag"
        name: "tag"
        pattern:
          - "^[^, ]+$"
          - "Only 1 tag is allowed with no spaces or commas"
      - label: "URL"
        name: "url"
      - label: Date
        name: date
        widget: date
  - name: "My Interests"
    label: Interests
    folder: "_me"
    editor:
      preview: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - name: "URL"
        label: url
